

function [channel_data_out, p_gn] = CHANNEL_DESIGN_PROCESS(tx_no_of, rx_no_of, data_in)
    % Create MIMO Channel Object
    chan_obj = comm.MIMOChannel('SampleRate', 1e6, ...
        'MaximumDopplerShift', 30, ...
        'NumTransmitAntennas', tx_no_of, ...
        'NumReceiveAntennas', rx_no_of, ...
        'TransmitCorrelationMatrix', eye(tx_no_of), ...
        'ReceiveCorrelationMatrix', eye(rx_no_of), ...
        'PathGainsOutputPort', true, ... % Corrected property name
        'FadingDistribution', 'Rayleigh');

    % Pass the input data through the channel
    [channel_data_out, p_gn] = chan_obj(data_in);
end
